server {
    listen 80;
    server_name localhost;

    # 1. 托管前端资源 (精准匹配分配给你们的二级目录)
    location /HSPC-atlas/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # ==========================================
    # 【新增】拦截 Cellxgene 根目录写死的静态资源请求
    # ==========================================
    location /static/ {
        # 统一代理给 5005 端口的实例（给 5006 也可以，资源是一样的）
        proxy_pass http://cellxgene-hspc:5005/static/;
    }

    # 【新增】同理，拦截可能存在的网页图标请求，防止控制台报 404 错误
    location = /favicon.ico {
        proxy_pass http://cellxgene-hspc:5005/favicon.ico;
    }
    # ==========================================

    # ==========================================
    # 【本次新增】拦截由 ../ 相对路径引发的错误请求
    # 因为不管是 hspc 还是 blood-atlas 页面，向上一级都会来到 /HSPC-atlas/browser/
    # ==========================================
    location /HSPC-atlas/browser/static/ {
        proxy_pass http://cellxgene-hspc:5005/static/;
    }
    # ==========================================

    # 2. HSPC 数据交互界面入口
    location /HSPC-atlas/browser/hspc/ {
        # 剥离前缀，转发给内部 5005 端口
        proxy_pass http://cellxgene-hspc:5005/;
        
        # 告诉 cellxgene 它的真实外部挂载路径 (防止静态资源漂移)
        proxy_set_header X-Forwarded-Prefix "/HSPC-atlas/browser/hspc";
        proxy_set_header X-Script-Name "/HSPC-atlas/browser/hspc";
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # 3. Blood Atlas 数据交互界面入口
    location /HSPC-atlas/browser/blood-atlas/ {
        # 剥离前缀，转发给内部 5006 端口
        proxy_pass http://cellxgene-blood:5006/;
        
        proxy_set_header X-Forwarded-Prefix "/HSPC-atlas/browser/blood-atlas";
        proxy_set_header X-Script-Name "/HSPC-atlas/browser/blood-atlas";
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}